#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/


spring:
  cloud:
    zookeeper:
      connect-string: localhost:2181


mybatis-plus:
mapper-locations: classpath:mapper/*.xml
